/* eslint-disable */
// biome-ignore lint: disable

// Generated with Shell Shock
// Note: Do not edit this file manually - it will be overwritten automatically

/**
 * The environment configuration module provides an interface to define environment configuration parameters.
 *
 * @module shell-shock:env
 */
declare module "shell-shock:env" {
  /**
   * Object
   *
   * @title Object
   *
   */
  export interface EnvBase {
    /**
     * The application's cached data directory.
     *
     * @title Cache Directory
     *
     */
    CACHE_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a continuous integration environment.
     *
     * @title Continuous Integration
     * @alias CONTINUOUS_INTEGRATION
     * @defaultValue false
     */
    CI: boolean;
    /**
     * The application's configuration data directory.
     *
     * @title Configuration Directory
     *
     */
    CONFIG_DIR?: string;
    /**
     * The application's runtime data directory.
     *
     * @title Data Directory
     *
     */
    DATA_DIR?: string;
    /**
     * Indicates if the application is running in debug mode.
     *
     * @defaultValue false
     */
    DEBUG: boolean;
    /**
     * The default locale to be used in the application.
     *
     * @defaultValue "en_US"
     */
    DEFAULT_LOCALE: string;
    /**
     * The default timezone for the application.
     *
     * @defaultValue "America/New_York"
     */
    DEFAULT_TIMEZONE: string;
    /**
     * A variable that specifies the [Devenv](https://devenv.sh/) runtime directory.
     *
     *
     */
    DEVENV_RUNTIME?: string;
    /**
     * The environment the application is running in. This value will be populated with the value of `MODE` if not provided.
     *
     * @defaultValue "production"
     */
    ENVIRONMENT: string;
    /**
     * A web page to lookup error messages and display additional information given an error code.
     *
     * @title Error Details URL
     *
     */
    ERROR_URL: string;
    /**
     * An indicator that specifies the current runtime is a force color environment.
     *
     * @defaultValue false
     */
    FORCE_COLOR: boolean | number;
    /**
     * An indicator that specifies the current runtime should force hyperlinks in terminal output.
     *
     * @defaultValue false
     */
    FORCE_HYPERLINK: boolean | number;
    /**
     * Indicates if error data should be included.
     *
     * @defaultValue false
     */
    INCLUDE_ERROR_DATA: boolean;
    /**
     * The application's logging directory.
     *
     * @title Log Directory
     *
     */
    LOG_DIR?: string;
    /**
     * The default lowest log level to accept. If `null`, the logger will reject all records.
     *
     * @defaultValue "info"
     */
    LOG_LEVEL?: "error" | "warn" | "info" | "debug" | null;
    /**
     * An indicator that specifies the current runtime is a minimal environment.
     *
     * @defaultValue false
     */
    MINIMAL: boolean;
    /**
     * The mode in which the application is running.
     *
     * @alias NODE_ENV
     *
     * @alias VERCEL_ENV
     * @defaultValue "production"
     */
    MODE: "development" | "test" | "production";
    /**
     * An indicator that specifies the current runtime is a no color environment.
     *
     * @defaultValue false
     */
    NO_COLOR: boolean;
    /**
     * The name of the organization that maintains the application.
     *
     * @alias ORG
     *
     */
    ORGANIZATION: string;
    /**
     * The platform for which the application was built.
     *
     * @defaultValue "neutral"
     */
    PLATFORM: "node" | "neutral" | "browser";
    /**
     * Indicates if error stack traces should be captured.
     *
     * @defaultValue false
     */
    STACKTRACE: boolean;
    /**
     * The application's temporary data directory.
     *
     * @title Temporary Directory
     *
     */
    TEMP_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a test environment.
     *
     * @defaultValue false
     */
    TEST: boolean;
    /**
     * The appcircle build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AC_APPCIRCLE?: string;
    /**
     * The name of the agent running the application. This variable is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AGENT_NAME?: string;
    /**
     * The agola git reference. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AGOLA_GIT_REF?: string;
    /**
     * The name of the application.
     *
     * @readonly
     *
     */
    readonly APP_NAME: string;
    /**
     * The version of the application.
     *
     * @readonly
     * @defaultValue "1.0.0"
     */
    readonly APP_VERSION: string;
    /**
     * The appcenter build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly APPCENTER_BUILD_ID?: string;
    /**
     * A variable that specifies the application data directory on Windows.
     *
     * @readonly
     *
     */
    readonly APPDATA?: string;
    /**
     * The appveyor build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly APPVEYOR?: string;
    /**
     * The bamboo plan key. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly bamboo_planKey?: string;
    /**
     * The bitbucket commit. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BITBUCKET_COMMIT?: string;
    /**
     * The bitrise build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BITRISE_IO?: string;
    /**
     * The buddy workspace ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUDDY_WORKSPACE_ID?: string;
    /**
     * A checksum hash created during the build.
     *
     * @readonly
     *
     */
    readonly BUILD_CHECKSUM: string;
    /**
     * The unique identifier for the build.
     *
     * @readonly
     *
     */
    readonly BUILD_ID: string;
    /**
     * The timestamp the build was ran at.
     *
     * @readonly
     *
     */
    readonly BUILD_TIMESTAMP: string;
    /**
     * The builder output build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUILDER_OUTPUT?: string;
    /**
     * The buildkite build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUILDKITE?: string;
    /**
     * The cf build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CF_BUILD_ID?: string;
    /**
     * The ci name. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CI_NAME?: string;
    /**
     * The xcode project build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CI_XCODE_PROJECT?: string;
    /**
     * The circleci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CIRCLECI?: string;
    /**
     * The cirrus-ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CIRRUS_CI?: string;
    /**
     * The cm build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CM_BUILD_ID?: string;
    /**
     * The codebuild build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CODEBUILD?: string;
    /**
     * The color terminal type. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly COLORTERM?: string;
    /**
     * The ConEmu task name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly ConEmuTask?: string;
    /**
     * The cursor trace ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly CURSOR_TRACE_ID?: string;
    /**
     * The drone build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly DRONE?: string;
    /**
     * The dsari build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly DSARI?: string;
    /**
     * The earthly build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly EARTHLY_CI?: string;
    /**
     * The eas build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly EAS_BUILD?: string;
    /**
     * The gerrit project. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GERRIT_PROJECT?: string;
    /**
     * The gitea actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITEA_ACTIONS?: string;
    /**
     * The github actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITHUB_ACTIONS?: string;
    /**
     * The gitlab ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITLAB_CI?: string;
    /**
     * The go cd build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GOCD?: string;
    /**
     * The harness build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly HARNESS_BUILD_ID?: string;
    /**
     * The hudson build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly HUDSON?: string;
    /**
     * The jenkins url. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly JENKINS_URL?: string;
    /**
     * The layerci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly LAYERCI?: string;
    /**
     * A variable that specifies the current user's local application data directory on Windows.
     *
     * @readonly
     *
     */
    readonly LOCALAPPDATA?: string;
    /**
     * The magnum build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly MAGNUM?: string;
    /**
     * The netlify build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NETLIFY?: string;
    /**
     * The nevercode build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NEVERCODE?: string;
    /**
     * The now builder build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NOW_BUILDER?: string;
    /**
     * The prow job ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly PROW_JOB_ID?: string;
    /**
     * The release build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RELEASE_BUILD_ID?: string;
    /**
     * The unique identifier for the release.
     *
     * @readonly
     *
     */
    readonly RELEASE_ID: string;
    /**
     * The tag for the release. This is generally in the format of "\<APP_NAME\>\@\<APP_VERSION\>".
     *
     * @readonly
     *
     */
    readonly RELEASE_TAG: string;
    /**
     * The render build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RENDER?: string;
    /**
     * The unique identifier for the current run. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RUN_ID?: string;
    /**
     * The sailci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SAILCI?: string;
    /**
     * The screwdriver build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SCREWDRIVER?: string;
    /**
     * The semaphore build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SEMAPHORE?: string;
    /**
     * The sourcehut build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SOURCEHUT?: string;
    /**
     * The spaceship build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SPACESHIP_CI?: string;
    /**
     * The strider build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly STRIDER?: string;
    /**
     * The task ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TASK_ID?: string;
    /**
     * The teamcity version. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TEAMCITY_VERSION?: string;
    /**
     * The terminal type. This variable is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TERM?: string;
    /**
     * The terminal program name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERM_PROGRAM?: string;
    /**
     * The terminal program version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERM_PROGRAM_VERSION?: string;
    /**
     * The terminal emulator name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERMINAL_EMULATOR?: string;
    /**
     * An indicator that specifies the current terminal is running Terminus Sublime. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERMINUS_SUBLIME?: boolean;
    /**
     * The task force build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TF_BUILD?: string;
    /**
     * The travis build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TRAVIS?: string;
    /**
     * The vela build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly VELA?: string;
    /**
     * The VTE version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly VTE_VERSION?: string;
    /**
     * The terminal emulator session ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly WT_SESSION?: string;
    /**
     * The xcode server build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly XCS?: string;
    /**
     * A variable that specifies the cache path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_CACHE_HOME?: string;
    /**
     * A variable that specifies the configuration path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_CONFIG_HOME?: string;
    /**
     * A variable that specifies the data path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_DATA_HOME?: string;
    /**
     * A variable that specifies the runtime directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_RUNTIME_DIR?: string;
    /**
     * A variable that specifies the state directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_STATE_HOME?: string;
  }
  /**
   * The environment configuration object with prefixed keys.
   *
   * @remarks
   * The `Env` type extends the `EnvBase` interface by including additional keys that are prefixed according to the project's configuration. This allows for flexibility in accessing environment variables with different naming conventions.
   */
  export type Env = {
    [Key in keyof EnvBase as
      | Key
      | `NEXT_${Key}`
      | `ONE_${Key}`
      | `PLAYGROUND_CLI_${Key}`
      | `POWERLINES_${Key}`
      | `SHELL_SHOCK_${Key}`
      | `STORM_STACK_${Key}`
      | `STORM_${Key}`
      | `VERCEL_${Key}`
      | `VITE_${Key}`]: EnvBase[Key];
  };
  /**
   * The initial environment configuration state for the Playground Command Line Interface project.
   *
   * @title Object
   *
   */
  export const initialEnv: Partial<EnvBase>;
  /**
   * The environment configuration serializer for the Powerlines application.
   *
   * @see https://deepkit.io/docs/serialization/serializers
   *
   * @see https://github.com/marcj/untitled-code/blob/master/packages/type/src/serializer.ts#L1918
   *
   * @remarks
   * This serializer is used to serialize and deserialize the Powerlines environment configuration.
   */
  export class EnvSerializer extends Serializer {
    /**
     * Initializes a new instance of the `EnvSerializer` class.
     */
    constructor();
  }
  /**
   * Serialize a environment configuration object to JSON data objects (not a JSON string).
   *
   * @remarks
   * The resulting JSON object can be stringified using `JSON.stringify()`.
   * @example
   * ```ts
   * const json = serializeEnv(env);
   * ```
   * @throws ValidationError when serialization or validation fails.
   *
   */
  export const serializeEnv: import("@powerlines/deepkit/vendor/type").SerializeFunction<
    EnvBase,
    any
  >;
  /**
   * Deserialize a environment configuration object from JSON data objects to JavaScript objects, without running any validators.
   *
   * @remarks
   * Types that are already correct will be used as-is.
   * @example
   * ```ts
   * const env = deserializeEnv(json);
   * ```
   * @throws ValidationError when deserialization fails.
   *
   */
  export const deserializeEnv: import("@powerlines/deepkit/vendor/type").SerializeFunction<
    any,
    EnvBase
  >;
  /**
   * Initializes the Powerlines environment configuration module.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   * @param environmentConfig - The dynamic/runtime configuration - this could
   *   include the current environment variables or any other environment-specific
   *   settings provided by the runtime.
   * @returns The initialized Powerlines configuration object.
   *
   */
  export function createEnv(environmentConfig?: Partial<Env>): Env;
  /**
   * The environment configuration object.
   *
   * @remarks
   * This object provides access to the environment configuration parameters in the application runtime.
   */
  export const env: Env;
  /**
   * Detect if the application is running in a continuous integration (CI) environment.
   */
  export const isCI: boolean;
  /**
   * Detect the \`mode\` of the current runtime environment.
   *
   * @remarks
   * The `mode` is determined by the `MODE` environment variable, or falls back to the `NEXT_PUBLIC_VERCEL_ENV`, `NODE_ENV`, or defaults to `production`. While the value can potentially be any string, it is generally recommended to only allow a value in the following list:
   *
   * - `production`
   *
   * - `test`
   *
   * - `development`
   */
  export const mode: string;
  /**
   * Detect if the application is running in `"production"` mode
   */
  export const isProduction: boolean;
  /**
   * Detect if the application is running in `"test"` mode
   */
  export const isTest: boolean;
  /**
   * Detect if the application is running in `"development"` mode
   */
  export const isDevelopment: boolean;
  /**
   * Detect if the application is currently being debugged
   */
  export const isDebug: boolean;
  /**
   * An indicator specifying whether the current operating system is MacOS (darwin kernel).
   */
  export const isWindows: boolean;
  /**
   * An indicator specifying whether the current operating system is Linux.
   */
  export const isLinux: boolean;
  /**
   * An indicator specifying whether the current operating system is MacOS (darwin kernel).
   */
  export const isMacOS: boolean;
  /**
   * The environment path types for storing things like data, config, logs, and cache in the current runtime environment.
   *
   * @remarks
   * These environment path types are accessed in the {@link EnvPaths} type.
   */
  export type EnvPathType = "data" | "config" | "cache" | "log" | "temp";
  /**
   * The environment paths for storing things like data, config, logs, and cache in the current runtime environment.
   */
  export type EnvPaths = Record<EnvPathType, string>;
  /**
   * The resolved application directories based on the current operating system and environment variables.
   *
   * @remarks
   * If the `DATA_DIR`, `CONFIG_DIR`, `CACHE_DIR`, `LOG_DIR`, or `TEMP_DIR` environment variables are set, they will be treated as overrides and used by default. If the environment variables are not set, the paths are determined based on the specific conventions for each operating system (with additional overrides available through operating system specific environment variables):
   *
   * - **Linux**: directories are generally created in `~/.config/<name>` (this is determined via the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/))
   *
   * - **Windows**: directories are generally created in `%AppData%/<name>`
   *
   * - **MacOS**: directories are generally created in `~/Library/Application Support/<name>`
   */
  export const paths: EnvPaths;
}

/**
 * A collection of application upgrade utility functions for Shell Shock.
 *
 * @module shell-shock:upgrade
 */
declare module "shell-shock:upgrade" {
  /**
   * Options for the `locateLockfile` handler function.
   */
  export interface LocateLockfileOptions {
    /**
     * The current working directory to use. If not provided, the process's current working directory will be used.
     */
    cwd?: string;
  }
  /**
   * Locate the lockfile currently being used by the command-line/workspace.
   *
   * @remarks
   * This function is used to determine the lockfile currently being used by the command-line/workspace. It can be used in the CLI upgrade command to check if the application is using npm, yarn, or another package manager.
   *
   *
   * @param options - The options for the `locateLockfile` function. Currently,
   *   there are no options available, but this parameter is included for future
   *   extensibility.
   * @returns A promise that resolves to the lockfile currently being used by the
   *   command-line/workspace as a string.
   *
   */
  export function locateLockfile(
    options?: LocateLockfileOptions
  ): Promise<string | undefined>;
  /**
   * Options for the `getPackageManager` handler function.
   */
  export type GetPackageManagerOptions = LocateLockfileOptions;
  /**
   * Get the package manager currently being used by the command-line/workspace.
   *
   * @remarks
   * This function is used to determine the package manager currently being used by the command-line/workspace. It can be used in the CLI upgrade command to check if the application is using npm, yarn, or another package manager.
   *
   *
   * @param options - The options for the `getPackageManager` function. Currently,
   *   there are no options available, but this parameter is included for future
   *   extensibility.
   * @returns A promise that resolves to the package manager currently being used
   *   by the command-line/workspace as a string.
   *
   */
  export function getPackageManager(
    options?: GetPackageManagerOptions
  ): Promise<Promise<"npm" | "yarn" | "deno" | "pnpm" | "bun">>;
  /**
   * Represents a maintainer of an npm package.
   */
  export interface NpmPackageMaintainer {
    /**
     * The email of the npm package maintainer.
     */
    email: string;
    /**
     * The username of the npm package maintainer.
     */
    username: string;
  }
  /**
   * Represents the links of an npm package.
   */
  export interface NpmPackageLinks {
    /**
     * The homepage of the npm package.
     */
    homepage?: string;
    /**
     * The repository of the npm package.
     */
    repository?: string;
    /**
     * The bugs page of the npm package.
     */
    bugs?: string;
    /**
     * The npm page of the npm package.
     */
    npm?: string;
  }
  /**
   * Represents an npm package.
   */
  export interface NpmPackage {
    /**
     * The name of the npm package.
     */
    name: string;
    /**
     * The date when the npm package was last updated.
     */
    date: Date;
    /**
     * The version of the npm package.
     */
    version: string;
    /**
     * The description of the npm package.
     */
    description?: string;
    /**
     * A list of keywords associated with the npm package.
     */
    keywords: string[];
    /**
     * The license of the npm package.
     */
    license?: string;
    /**
     * The maintainers of the npm package.
     */
    maintainers: NpmPackageMaintainer[];
    /**
     * The links of the npm package.
     */
    links: NpmPackageLinks;
  }
  /**
   * Represents an npm package search result item.
   */
  export interface NpmPackageSearchResultItem {
    /**
     * The npm package details.
     */
    package: NpmPackage;
  }
  /**
   * Represents an npm package search result.
   */
  export interface NpmPackageSearchResult {
    /**
     * The list of npm package search result items.
     */
    objects: NpmPackageSearchResultItem[];
  }
  /**
   * Fetch details of an npm package.
   *
   * @remarks
   * This function is used to fetch an npm package. It can be used in the CLI upgrade command to check if the application is using npm, yarn, or another package manager.
   *
   *
   * @param packageName - The name of the npm package to fetch.
   * @returns A promise that resolves to the npm package details or undefined if
   *   the package is not found.
   *
   */
  export function fetchNpmPackage(
    packageName: string
  ): Promise<Promise<NpmPackage | undefined>>;
  /**
   * Get the latest version of the application from the npm registry.
   *
   * @remarks
   * This function is used to retrieve the latest version of the application from the npm registry. It can be used in the CLI upgrade command to check if there is a newer version of the application available.
   *
   *
   * @param packageName - The name of the npm package to fetch.
   * @returns A promise that resolves to the latest version of the specified npm
   *   package as a string.
   *
   */
  export function getLatest(packageName: string): Promise<string | undefined>;
  /**
   * Options for the `install` handler function.
   */
  export interface InstallOptions {
    /**
     * A callback function that is called with the stdout output of the command.
     */
    stdout?: (string: any) => void;
    /**
     * A callback function that is called with the stderr output of the command.
     */
    stderr?: (string: any) => void;
    /**
     * Whether to enable color output in the command. If not provided, color output will be enabled by default.
     */
    color?: boolean;
  }
  /**
   * Install the application dependencies.
   *
   * @remarks
   * This function is used to install the application dependencies. It can be used in the CLI upgrade command to ensure that all necessary dependencies are installed.
   *
   *
   * @param options - The options for the `install` function. Currently, there are
   *   no options available, but this parameter is included for future
   *   extensibility.
   * @returns A promise that resolves when the installation of dependencies is
   *   complete.
   *
   */
  export function install(options?: InstallOptions): Promise<Promise<string>>;
}

/**
 * A collection of helper utilities that ease command-line application development.
 *
 * @module shell-shock:utils
 */
declare module "shell-shock:utils" {
  import { AsyncLocalStorage } from "node:async_hooks";
  /**
   * The global Shell Shock - Application context instance.
   *
   * @internal
   */
  export let internal_appContext: AsyncLocalStorage<Map<string, any>>;
  /**
   * Get the Shell Shock - Application context for the current application.
   *
   * @param options - The options to use when getting the context.
   * @returns The Shell Shock - Application context for the current application or undefined if the context is not available.
   */
  export function useApp(): Map<string, any> | undefined;
  /**
   * A utility hook function to get the command line arguments from the application context.
   *
   * @returns An array of command-line arguments from the application context.
   * @throws If the application context is not available.
   */
  export function useArgs(): string[];
  /**
   * The context object for the current command execution, containing the command path and segments.
   */
  export interface CommandContext {
    path: string;
    segments: string[];
  }
  /**
   * The global Shell Shock - Command context instance.
   *
   * @internal
   */
  export let internal_commandContext: AsyncLocalStorage<CommandContext>;
  /**
   * Get the Shell Shock - Command context for the current application.
   *
   * @param options - The options to use when getting the context.
   * @returns The Shell Shock - Command context for the current application.
   * @throws If the Shell Shock - Command context is not available.
   */
  export function useCommand(): CommandContext;
  /**
   * A utility hook function to get the individual segments of the current command path.
   *
   * @returns An array of command path segments.
   * @throws If the command context is not available.
   */
  export function useSegments(): string[];
  /**
   * A utility hook function to get the full command path as a string.
   *
   * @returns The full command path as a string.
   * @throws If the command context is not available.
   */
  export function usePath(): string;
  /**
   * Retrieves the command-line arguments from Deno or Node.js environments.
   *
   * @remarks
   * This function is only intended for internal use. Please use `useArgs()` instead.
   *
   *
   * @internal
   *
   *
   *
   * @returns An array of command-line arguments from Deno or Node.js
   *   environments.
   *
   */
  export function getArgs(): string[];
  /**
   * Checks if a specific flag is present in the command-line arguments.
   *
   * @see https://github.com/sindresorhus/has-flag/blob/main/index.js
   *
   * @param flag - The flag (or an array of flags/aliases) to check for, e.g.,
   *   "color", "no-color".
   * @param argv - The command-line arguments to check against. Defaults to global
   *   Deno args or process args.
   * @returns True if the flag is present, false otherwise.
   *
   */
  export function hasFlag(flag: string | string[], argv?: string[]): boolean;
  export const isHelp: boolean;
  /**
   * Detect if stdout.TTY is available
   */
  export const isTTY: boolean;
  /**
   * Detect if the current environment is minimal (CI, non-TTY, etc.)
   */
  export const isMinimal: any;
  /**
   * Detect if the current environment is interactive
   */
  export const isInteractive: boolean;
  /**
   * Check if the current environment/terminal supports hyperlinks in the terminal.
   *
   * @returns True if the current environment/terminal supports hyperlinks.
   *
   */
  export function isHyperlinkSupported(): boolean;
  /**
   * Options for the getColorSupportLevel function
   */
  export interface GetColorSupportLevelOptions {
    /**
     * Indicates if the function should skip checking command-line flags for color support
     */
    ignoreFlags: boolean;
  }
  /**
   * Checks if a specific flag is present in the command-line arguments.
   *
   * @see https://github.com/sindresorhus/has-flag/blob/main/index.js
   *
   * @param flag - The flag to check for, e.g., "color", "no-color".
   * @param argv - The command-line arguments to check against. Defaults to global
   *   Deno args or process args.
   * @returns True if the flag is present, false otherwise.
   *
   */
  export function getColorSupportLevel(
    stream: NodeJS.WriteStream & {
      fd: 1 | 2;
    },
    options?: GetColorSupportLevelOptions
  ):
    | false
    | 0
    | 2
    | 3
    | {
        level: number;
        hasBasic: boolean;
        has256: boolean;
        has16m: boolean;
      };
  /**
   * Detect the terminal color support level in the current environment
   */
  export const colorSupportLevels: {
    stdout:
      | number
      | boolean
      | {
          level: number;
          hasBasic: boolean;
          has256: boolean;
          has16m: boolean;
        };
    stderr:
      | number
      | boolean
      | {
          level: number;
          hasBasic: boolean;
          has256: boolean;
          has16m: boolean;
        };
  };
  /**
   * Detect if terminal color is supported in the current environment
   */
  export const isColorSupported: boolean;
  /**
   * Detect if Unicode characters are supported in the current environment
   */
  export const isUnicodeSupported: boolean;
  /**
   * Options for the exit handler function.
   */
  export interface ExitOptions {
    /**
     * An optional exception that caused the exit. This can be a string message or an Error object.
     */
    exception?: string | Error;
    /**
     * Indicates whether the exit function should manually exit the process or not. If set to true, the exit function will not call process.exit() and will allow the application to continue running. If set to false or not specified, the exit function will call process.exit() to terminate the application.
     */
    skipProcessExit?: boolean;
    /**
     * Indicates whether the exit function should perform synchronous operations only. If set to true, the exit function will avoid any asynchronous operations during exit. If set to false or not specified, the exit function may perform asynchronous operations as needed.
     */
    isSynchronous?: boolean;
    /**
     * The signal number that triggered the exit. This is typically used when the shutdown is initiated by a system signal (e.g., SIGINT, SIGTERM).
     */
    signal?: number;
    /**
     * A Date object representing the timestamp when the process started. This can be used to measure the duration of the shutdown process.
     */
    startDate?: Date;
  }
  export function exit(options?: ExitOptions): Promise<void>;
}

/**
 * A collection of helper utilities to assist in generating content meant for display in the console.
 *
 * @module shell-shock:console
 */
declare module "shell-shock:console" {
  /**
   * The ASCII Bell character, which can be used to trigger a beep sound in the console.
   */
  export const beep = "\u0007";
  /**
   * An object containing ANSI escape codes for controlling the console cursor.
   */
  export const cursor: {
    to(x: any, y: any): string;
    move(x: any, y: any): string;
    up: (count?: number) => string;
    down: (count?: number) => string;
    forward: (count?: number) => string;
    backward: (count?: number) => string;
    nextLine: (count?: number) => string;
    prevLine: (count?: number) => string;
    left: string;
    hide: string;
    show: string;
    save: string;
    restore: string;
  };
  /**
   * An object containing ANSI escape codes for erasing parts of the console.
   */
  export const erase: {
    screen: string;
    up: (count?: number) => string;
    down: (count?: number) => string;
    line: string;
    lineEnd: string;
    lineStart: string;
    lines(count: any): string;
  };
  /**
   * An object containing ANSI escape codes for scrolling the console.
   */
  export const scroll: {
    up: (count?: number) => string;
    down: (count?: number) => string;
  };
  /**
   * A helper function to clear the console based on a count of lines
   *
   * @param {string} current - The current console output to be cleared
   * @param {number} consoleWidth - The number of characters per line in the
   *   console
   */
  export function clear(current: string, consoleWidth: number): string;
  /**
   * Removes ANSI escape codes from a string.
   *
   * @example
   * ```ts
   * const result = stripAnsi("Hello\\x1b[31mWorld\\x1b[0mAgain"); // "HelloWorldAgain"
   * ```
   * @param text - The text to strip ANSI codes from.
   * @returns The text with ANSI codes removed.
   *
   */
  export function stripAnsi(text: string | number): string;
  /**
   * The available ANSI colors for console text.
   */
  export type AnsiColor =
    | "reset"
    | "bold"
    | "dim"
    | "italic"
    | "underline"
    | "overline"
    | "inverse"
    | "hidden"
    | "strikethrough"
    | "black"
    | "red"
    | "green"
    | "yellow"
    | "blue"
    | "magenta"
    | "cyan"
    | "white"
    | "blackBright"
    | "gray"
    | "grey"
    | "redBright"
    | "greenBright"
    | "yellowBright"
    | "blueBright"
    | "magentaBright"
    | "cyanBright"
    | "whiteBright"
    | "bgBlack"
    | "bgRed"
    | "bgGreen"
    | "bgYellow"
    | "bgBlue"
    | "bgMagenta"
    | "bgCyan"
    | "bgWhite"
    | "bgBlackBright"
    | "bgGray"
    | "bgGrey"
    | "bgRedBright"
    | "bgGreenBright"
    | "bgYellowBright"
    | "bgBlueBright"
    | "bgMagentaBright"
    | "bgCyanBright"
    | "bgWhiteBright";
  /**
   * A recursive type that defines theme colors for console text.
   *
   * @remarks
   * This type allows for nested theme color definitions, enabling complex theming structures for console applications.
   */
  export type ThemeColors<T> = T extends object
    ? {
        [K in keyof T]: ThemeColors<T[K]>;
      }
    : (text: string) => string;
  /**
   * An object containing functions for coloring console applications. Each function corresponds to a terminal color. See {@link AnsiColor} for available colors.
   */
  export type Colors = Record<AnsiColor, (text: string) => string> &
    ThemeColors<ThemeColorsResolvedConfig>;
  /**
   * An object containing functions for coloring console applications. Each function corresponds to a terminal color. See {@link Colors} for available colors.
   */
  export const colors: Colors;
  /**
   * Split text into multiple lines based on a maximum length.
   *
   * @remarks
   * This function splits the provided text into multiple lines based on the specified maximum length, ensuring that words are not broken in the middle.
   *
   * @param text - The text to split into multiple lines.
   * @param maxLength - The maximum length of each line.
   */
  export function splitText(
    text: string,
    maxLength: number | SizeToken
  ): string[];
  /**
   * Options for writing a line to the console.
   */
  export interface WriteLineOptions {
    /**
     * Padding to apply to the line
     *
     * @remarks
     * The amount of padding (in spaces) to apply to the line when writing to the console. This value is applied to both the left and right sides of the line. If not specified, the default padding defined in the current theme configuration will be used.
     */
    padding?: number;
    /**
     * Console function to use for writing the line
     *
     * @remarks
     * The console function to use for writing the line. If not specified, the default console function `console.log` will be used.
     *
     * @defaultValue `console.log`
     */
    consoleFn?: (text: string) => void;
    /**
     * Color of the line text
     *
     * @remarks
     * The color to apply to the line text when writing to the console. This can be one of the predefined color themes: "primary", "secondary", or "tertiary". If not specified, no specific coloring will be applied to the text (the default/system terminal text color will likely be used).
     *
     */
    color?: "primary" | "secondary" | "tertiary";
  }
  /**
   * Write a line to the console.
   *
   * @remarks
   * This function writes a line to the console, applying the appropriate padding as defined in the current theme configuration and wrapping as needed.
   *
   * @param text - The line text to write to the console.
   * @param options - The options to apply when writing the line to the console.
   */
  export function writeLine(
    text?: string | number | boolean | null,
    options?: WriteLineOptions
  ): void;
  /**
   * Render a hyperlink in the console.
   *
   * @param url - The URL to render as a hyperlink.
   * @param text - The text to display for the link. If not provided, the URL will
   *   be used as the text.
   * @returns The formatted hyperlink string.
   *
   */
  export function link(url: string, text?: string): string;
  /**
   * Options for formatting the divider line written to console.
   */
  export interface DividerOptions {
    /**
     * The width of the divider line. If not specified, the divider will span the full width of the console, minus the padding.
     */
    width?: number;
    /**
     * The border of the divider line. Can be 'primary', 'secondary', 'tertiary', or 'none'. If not specified, the default border style will be used.
     *
     * @remarks
     * The value provided will determine the border style and color based on the current theme configuration.
     * @defaultValue "primary"
     */
    /**
     * The border style/color of the divider line. Can be 'primary', 'secondary', 'tertiary', or 'none'. If not specified, the default border style will be used.
     */
    border?: "primary" | "secondary" | "tertiary";
    /**
     * Padding to apply to the line
     *
     * @remarks
     * The amount of padding (in spaces) to apply to the line when writing to the console. This value is applied to both the left and right sides of the line. If not specified, the default padding defined in the current theme configuration will be used.
     * @defaultValue 0
     */
    padding?: number;
  }
  /**
   * Write a divider line to the console.
   *
   * @example
   * ```ts
   * divider({ width: 50, border: "primary" }); // Writes a divider line of width 50 with primary border.
   * ```
   * @param options - Options for formatting the divider line.
   */
  export function divider(options: DividerOptions): void;
  /**
   * Write a help message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function help(message: string): void;
  /**
   * Write a success message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function success(message: string): void;
  /**
   * Write an informational message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function info(message: string): void;
  /**
   * Write a debug message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function debug(message: string): void;
  /**
   * Write a verbose message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function verbose(message: string): void;
  /**
   * Write a warning message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function warn(message: string): void;
  /**
   * Write a destructive/danger message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function danger(message: string): void;
  /**
   * Write an error message to the console.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   *
   * @param message - The message to write to the console.
   */
  export function error(err: string | Error): void;
  /**
   * A type representing the width size of an item in the console.
   */
  export type SizeToken =
    | "full"
    | "1/1"
    | "1/2"
    | "1/3"
    | "1/4"
    | "1/5"
    | "1/6"
    | "1/12"
    | "1/24"
    | "100%"
    | "50%"
    | "33.33%"
    | "25%"
    | "20%"
    | "10%"
    | "5%"
    | "2.5%";
  /**
   * Determine if a value is a valid size token.
   *
   * @remarks
   * This function checks if the provided value is a valid size token, which can be one of the predefined strings representing common width sizes (e.g., "full", "1/2", "1/3", etc.) or percentage strings (e.g., "50%").
   * @param value - The value to check for being a valid size token.
   * @returns True if the value is a valid size token, false otherwise.
   *
   */
  /**
   * Determines if the provided value is a valid size token.
   *
   * @param {any} value
   */
  export function isSizeToken(value: any): value is SizeToken;
  /**
   * Calculate the width in characters based on the provided width size.
   *
   * @remarks
   * This function calculates the width in characters based on the provided width size, which can be a predefined string (e.g., "full", "1/2", "1/3", etc.) or a percentage string (e.g., "50%"). The calculation is based on the current width of the console (process.stdout.columns).
   * @param size - The width size to calculate. This can be a predefined string
   *   (e.g., "full", "1/2", "1/3", etc.) or a percentage string (e.g., "50%").
   * @returns The calculated width in characters.
   *
   */
  export function calculateWidth(size: SizeToken): number; /**
   * The border options applied to table cells.
   */
  export type BorderOption =
    | "primary"
    | "secondary"
    | "tertiary"
    | "none"
    | string;
  /**
   * Options to customize the output of the {@link table} function.
   */
  export interface TableOutputOptions {
    /**
     * Border variant for the table cell.
     *
     * @remarks
     * The border variant to use for the table cell. This determines the color and style of the border around the cell.
     *
     * @defaultValue primary
     */
    border?:
      | BorderOption
      | {
          top?: BorderOption;
          right?: BorderOption;
          bottom?: BorderOption;
          left?: BorderOption;
          topLeft?: BorderOption;
          topRight?: BorderOption;
          bottomLeft?: BorderOption;
          bottomRight?: BorderOption;
        };
    /**
     * Padding for the table cell.
     *
     * @remarks
     * The amount of padding (in spaces) to apply to the table cell. This value is applied to both the left and right sides of the cell. If not specified, the default table padding defined in the current theme configuration will be used.
     *
     * @defaultValue `1`
     */
    padding?: number;
    /**
     * Alignment for the table cell.
     *
     * @remarks
     * The alignment for the table cell. This determines how the text within the cell is aligned. If not specified, the default alignment is "left".
     *
     * @defaultValue left
     */
    align?: "left" | "right" | "center";
  }
  /**
   * Options for a specific table cell provided to the {@link table} function.
   */
  export interface TableCellOptions extends TableOutputOptions {
    /**
     * The actual string value of the table cell.
     */
    value?: string;
    /**
     * Width of the table cell.
     *
     * @remarks
     * The width of the table cell (where 1 is a single character in the terminal). If not specified, the width will be determined based on the content of the cell and the available space in the console.
     */
    maxWidth: number | SizeToken | undefined;
  }
  /**
   * Options for a specific table row provided to the {@link table} function.
   */
  export interface TableRowOptions extends TableOutputOptions {
    /**
     * The actual string values of the table row's cells.
     */
    values?: (string | TableCellOptions)[];
  }
  /**
   * Options for a specific table cell provided to the {@link table} function.
   */
  export interface TableOptions extends TableOutputOptions {
    /**
     * The actual string values of the table's rows' cells.
     */
    values?: (string | TableCellOptions)[][];
  }
  /**
   * Write a table to the console.
   *
   * @remarks
   * This function writes a table to the console, applying the appropriate padding as defined in the current theme configuration and wrapping as needed.
   *
   * @param options - Options to customize the table output.
   */
  export function table(
    options:
      | TableOptions
      | TableRowOptions[]
      | TableCellOptions[][]
      | string[]
      | string[][]
  ): void;
}

/**
 * A collection of prompts that allow for interactive input in command-line applications.
 *
 * @module shell-shock:prompts
 */
declare module "shell-shock:prompts" {
  import EventEmitter from "node:events";
  import readline from "node:readline";
  /**
   * A utility function to pause execution for a specified duration, which can be used in prompt interactions to create delays or timeouts. The function returns a promise that resolves after the specified duration in milliseconds, allowing it to be used with async/await syntax for easier handling of asynchronous prompt logic.
   *
   * @param duration - The duration to sleep in milliseconds.
   * @returns A promise that resolves after the specified duration, allowing for
   *   asynchronous delays in prompt interactions.
   *
   */
  export function sleep(duration: number): Promise<void>;
  /**
   * A type for a custom prompt input parser, which can be used to create custom input styles for prompts. The function should return the parsed value for the given input string.
   */
  export type PromptParser<TValue = string> = (
    this: Prompt<TValue>,
    input: string
  ) => TValue;
  /**
   * A type for a custom prompt input formatter, which can be used to create custom display styles for prompts. The function should return the formatted string to display for the given input value.
   */
  export type PromptFormatter<TValue = string> = (
    this: Prompt<TValue>,
    input: TValue
  ) => string;
  /**
   * A built-in prompt mask function that just returns the input as is, making it
   * invisible
   *
   * @param {string} input
   */
  export function noMask(input: string): string;
  /**
   * A built-in prompt mask function that makes input invisible
   *
   * @param {string} input
   */
  export function invisibleMask(input: string): string;
  /**
   * The current state of a prompt
   */
  export interface PromptState<TValue = string> {
    /**
     * The current value of the prompt
     */
    value: TValue;
    /**
     * Indicates whether the prompt is in an error state
     */
    isError: boolean;
    /**
     * If the prompt is in an error state, this will contain the error message to display
     */
    errorMessage?: string;
    /**
     * Indicates whether the prompt is submitted
     */
    isSubmitted: boolean;
    /**
     * Indicates whether the prompt is cancelled
     */
    isCancelled: boolean;
    /**
     * Indicates whether the prompt is completed, which can be used to indicate that the prompt interaction is finished regardless of whether it was submitted or cancelled
     */
    isCompleted: boolean;
  }
  /**
   * Configuration options for creating a prompt
   */
  interface PromptConfig<TValue = string> {
    /**
     * The readable stream to use for prompt input, defaults to process.stdin
     */
    input?: NodeJS.ReadStream;
    /**
     * The writable stream to use for prompt output, defaults to process.stdout
     */
    output?: NodeJS.WriteStream;
    /**
     * The prompt message to display
     */
    message: string;
    /**
     * The prompt description message to display
     */
    description?: string;
    /**
     * The initial value of the prompt
     */
    initialValue?: TValue;
    /**
     * A validation function that returns true if the input is valid, false or a string error message if the input is invalid
     */
    validate?: (value: TValue) =>
      | boolean
      | string
      | {
          type: "error" | "warning";
          message: string;
        }
      | null
      | undefined
      | Promise<
          | boolean
          | string
          | {
              type: "error" | "warning";
              message: string;
            }
          | null
          | undefined
        >;
    /**
     * A function that parses the input value and returns the parsed result or throws an error if the input is invalid
     */
    parse?: PromptParser<TValue>;
    /**
     * A function that formats the input value and returns the formatted result or throws an error if the input is invalid
     */
    format?: PromptFormatter<TValue>;
    /**
     * A function that masks the input value and returns the masked result. This can be used to create password inputs or other sensitive input types where the actual input value should not be displayed. If not provided, the prompt will display the input as is without masking.
     */
    mask?: (input: string) => string;
    /**
     * A function that masks the value submitted by the user so that it can then be used in the console output or elsewhere without exposing sensitive information. If not provided, the prompt will use the same mask function for both input and submitted value masking.
     */
    maskSubmitted?: (input: string) => string;
    /**
     * The default error message to display when validation fails
     */
    defaultErrorMessage?: string;
    /**
     * The timeout duration in milliseconds for the prompt. If none is provided, the prompt will not time out.
     */
    timeout?: number;
  }
  /**
   * Base prompt class that other prompt types can extend from
   */
  abstract class Prompt<TValue = string> extends EventEmitter {
    protected config: PromptConfig<TValue>;
    protected abstract initialValue: TValue;
    protected input: NodeJS.ReadStream;
    protected output: NodeJS.WriteStream;
    protected message: string;
    protected description: string;
    protected errorMessage: string | null;
    protected defaultErrorMessage: string;
    protected isSubmitted: boolean;
    protected isCancelled: boolean;
    protected isInitial: boolean;
    protected consoleOutput: string;
    protected consoleStatus: string;
    protected displayValue: string;
    protected validator: (
      value: TValue
    ) =>
      | boolean
      | string
      | null
      | undefined
      | Promise<boolean | string | null | undefined>;
    protected parser: PromptParser<TValue>;
    protected formatter: PromptFormatter<TValue>;
    protected mask: (input: string) => string;
    protected maskSubmitted: (input: string) => string;
    protected cursor: number;
    protected cursorOffset: number;
    protected cursorHidden: boolean;
    constructor(config: PromptConfig<TValue>);
    /**
     * A getter for the prompt value that returns the current value or the initial value if the current value is not set
     */
    get value(): TValue;
    get isError(): boolean;
    protected get isSelect(): boolean;
    protected get isCompleted(): boolean;
    protected get isPlaceholder(): boolean;
    protected get status(): string;
    /**
     * A method to change the prompt value, which also updates the display value and fires a state update event. This method can be called by subclasses whenever the prompt value needs to be updated based on user input or other interactions.
     *
     * @param value
     */
    protected changeValue(value: TValue): void;
    /**
     * A method to emit the current state
     */
    protected sync(): void;
    /**
     * A method to ring the bell
     */
    protected bell(): void;
    /**
     * A method to handle keypress events and determine the corresponding action
     *
     * @param char
     * @param key
     */
    protected onKeypress(char: string, key: readline.Key): void;
    /**
     * A method to handle keypress events and determine the corresponding action
     *
     * @param char
     * @param key
     */
    protected keypress(char: string, key: readline.Key): void;
    /**
     * A method to close the prompt and clean up resources, which also emits a submit or cancel event based on the prompt state. This method should be called when the prompt interaction is finished and the prompt needs to be closed.
     */
    protected close(): Promise<void>;
    /**
     * A method to validate the prompt input using the provided validator function, which updates the error message and error state based on the validation result. This method is called whenever the prompt value changes and needs to be validated.
     *
     * @param value
     */
    protected validate(value: TValue): Promise<void>;
    /**
     * A method to route keypress events to specific prompt actions based on the key pressed. This method maps various key combinations and keys to corresponding actions that can be handled by the prompt, such as submitting, cancelling, navigating, etc.
     *
     * @param key
     */
    protected getAction(key: readline.Key): string | false;
    /**
     * A method to reset the prompt input
     */
    protected reset(): void;
    /**
     * A method to cancel the prompt input
     */
    protected cancel(): void;
    /**
     * A method to submit the prompt input
     */
    protected submit(): Promise<void>;
    /**
     * A method to render the prompt
     */
    protected invokeRender(): void;
    /**
     * A method to render the prompt
     */
    protected render(): string;
  }
  /**
   * Configuration options for creating a prompt with a prompt factory function
   */
  interface PromptFactoryConfig<TValue = string> extends PromptConfig<TValue> {
    /**
     * A function that is called when the prompt state changes, useful for updating the prompt message or other properties dynamically
     */
    onState?: (state: PromptState<TValue>) => any;
    /**
     * A function that is called when the prompt is submitted, useful for handling the submitted value or performing actions based on the prompt state
     */
    onSubmit?: (value: TValue) => any;
    /**
     * A function that is called when the prompt is canceled, useful for handling the canceled value or performing actions based on the prompt state
     */
    onCancel?: (event: any) => any;
  }
  /**
   * A unique symbol used to indicate that a prompt was cancelled, which can be returned from a prompt function to signal that the prompt interaction should be cancelled and any pending promises should be rejected with this symbol. This allows for a consistent way to handle prompt cancellations across different prompt types and interactions.
   */
  export const CANCEL_SYMBOL: unique symbol;
  /**
   * A utility function to check if a given value is the {@link CANCEL_SYMBOL | cancel symbol}, which can be used to determine if a prompt interaction was cancelled based on the value returned from a prompt factory function. This function checks if the provided value is strictly equal to the {@link CANCEL_SYMBOL | CANCEL_SYMBOL}, allowing for a consistent way to handle prompt cancellations across different prompt types and interactions.
   *
   * @param value - The value to check.
   * @returns A boolean indicating whether the provided value is the {@link
   *   CANCEL_SYMBOL | cancel symbol}, which can be used to determine if a prompt
   *   interaction was cancelled.
   *
   */
  export function isCancel(value: any): value is typeof CANCEL_SYMBOL;
  /**
   * Configuration options for creating a text-based prompt
   */
  interface StringPromptConfig extends PromptConfig<string> {
    /**
     * The initial value of the prompt
     */
    initialValue?: string;
    /**
     * A function that masks the input value and returns the masked result
     */
    mask?: (input: string) => string;
  }
  /**
   * A type definition for the configuration options to pass to the text prompt, which extends the base PromptConfig with additional options specific to text prompts. This type can be used when creating a text prompt using the {@link text | text prompt factory function} or when manually creating an instance of the TextPrompt class. The TextConfig type includes all the properties of the base PromptConfig, such as message, description, initialValue, validate, parse, format, mask, etc., as well as any additional properties that are specific to text prompts.
   */
  export type TextConfig = PromptFactoryConfig<string> & StringPromptConfig;
  /**
   * A function to create and run a text prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @remarks
   * This function can be used to easily create and run a text prompt without needing to manually create an instance of the TextPrompt class and handle its events. The function accepts a configuration object that extends the base PromptFactoryConfig with additional options specific to text prompts, such as the initial value and mask function. The returned promise allows for easy handling of the prompt result using async/await syntax or traditional promise chaining.
   * @example
   * ```ts
   * import { text, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const name = await text({
   *     message: "What is your name?",
   *     description: "Please enter your full name",
   *     validate: value => value.trim().length > 0 || "Name cannot be empty"
   *   });
   *   if (isCancel(name)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("Hello, " + name + "!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the text prompt, which
   *   extends the base PromptConfig with additional options specific to text
   *   prompts
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function text(config: TextConfig): Promise<string | symbol>;
  /**
   * Configuration for an option the user can select from the select prompt
   */
  interface PromptOptionConfig<TValue = string> {
    /**
     * The message label for the option
     */
    label?: string;
    /**
     * An icon for the option
     */
    icon?: string;
    /**
     * The value of the option
     */
    value: TValue;
    /**
     * The description of the option
     */
    description?: string;
    /**
     * Whether the option is selected
     */
    selected?: boolean;
    /**
     * Whether the option is disabled
     */
    disabled?: boolean;
  }
  /**
   * An option the user can select from the select prompt
   */
  export interface PromptOption<
    TValue = string
  > extends PromptOptionConfig<TValue> {
    /**
     * The message label for the option
     */
    label: string; /**
     * The index of the option
     */
    index: number;
    /**
     * Whether the option is selected
     */
    selected: boolean;
    /**
     * Whether the option is disabled
     */
    disabled: boolean;
  }
  /**
   * An options object for configuring a select prompt
   */
  interface SelectPromptConfig<TValue = string> extends PromptConfig<TValue> {
    /**
     * A hint to display to the user
     */
    hint?: string;
    /**
     * The options available for the select prompt
     */
    options: Array<string | PromptOptionConfig<TValue>>;
    /**
     * The number of options to display per page, defaults to 8
     */
    optionsPerPage?: number;
  }
  /**
   * A type definition for the configuration options to pass to the select prompt, which extends the base PromptConfig with additional options specific to select prompts. This type can be used when creating a select prompt using the {@link select | select prompt factory function}.
   *
   * @remarks
   * The Select Config type includes all the properties of the base PromptConfig, such as message, description, initialValue, validate, parse, format, etc., as well as any additional properties that are specific to select prompts, such as the list of options and pagination settings.
   */
  export type SelectConfig = PromptFactoryConfig<string> & SelectPromptConfig;
  /**
   * A function to create and run a select prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @example
   * ```ts
   * import { select, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const color = await select({
   *     message: "What is your favorite color?",
   *     description: "Please select your favorite color",
   *     validate: value => value.trim().length > 0 || "Color cannot be empty",
   *     options: [
   *       { label: "Red", value: "red", description: "The color of fire and blood" },
   *       { label: "Green", value: "green", description: "The color of nature and growth" },
   *       { label: "Blue", value: "blue", description: "The color of the sky and sea" },
   *       { label: "Yellow", value: "yellow", description: "The color of sunshine and happiness" }
   *     ]
   *   });
   *   if (isCancel(color)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("Your favorite color is " + color + "!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the select prompt, which
   *   extends the base PromptConfig with additional options specific to select
   *   prompts
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function select(config: SelectConfig): Promise<string | symbol>;
  /**
   * Configuration options for creating a numeric prompt
   */
  interface NumberPromptConfig extends PromptConfig<number> {
    /**
     * Whether the prompt should accept floating point numbers
     */
    isFloat?: boolean;
    /**
     * The number of decimal places to round the input to, defaults to 2
     */
    precision?: number;
    /**
     * The increment value for the number prompt, defaults to 1
     */
    increment?: number;
    /**
     * The minimum value for the number prompt, defaults to -Infinity
     */
    min?: number;
    /**
     * The maximum value for the number prompt, defaults to Infinity
     */
    max?: number;
  }
  /**
   * An object representing the configuration options for a numeric prompt.
   */
  export type NumericConfig = PromptFactoryConfig<number> & NumberPromptConfig;
  /**
   * A function to create and run a numeric prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @example
   * ```ts
   * import { numeric, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const age = await numeric({
   *     message: "How old are you?",
   *     description: "Please enter your age in years",
   *     validate: value => value < 21 ? "You must be at least 21 years old" : true,
   *   });
   *   if (isCancel(age)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("Your age is " + age + "!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the numeric prompt,
   *   which extends the base PromptFactoryConfig with additional options specific
   *   to numeric prompts
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function numeric(config: NumericConfig): Promise<number | symbol>;
  /**
   * Configuration options for creating a boolean toggle prompt
   */
  export interface TogglePromptConfig extends PromptConfig<boolean> {
    /**
     * The message for the true state of the prompt
     */
    trueMessage?: string;
    /**
     * The message for the false state of the prompt
     */
    falseMessage?: string;
  }
  /**
   * A prompt for toggling a boolean input
   */
  export class TogglePrompt extends Prompt<boolean> {
    protected initialValue: boolean;
    protected trueMessage: string;
    protected falseMessage: string;
    protected cursorHidden: boolean;
    constructor(config: TogglePromptConfig);
    /**
     * Update the toggle value to a checked state based on user input
     */
    protected check(): void;
    /**
     * Update the toggle value to an unchecked state based on user input
     */
    protected uncheck(): void;
    /**
     * A method to handle keypress events and determine the corresponding action
     *
     * @param char
     * @param key
     */
    protected keypress(char: string, key: readline.Key): any;
    /**
     * A method to delete the character backward of the cursor
     */
    protected delete(): void;
    /**
     * A method to move the cursor to the left
     */
    protected left(): void;
    /**
     * A method to move the cursor to the right
     */
    protected right(): void;
    /**
     * A method to move the cursor to down
     */
    protected down(): void;
    /**
     * A method to move the cursor to up
     */
    protected up(): void;
    /**
     * A method to move to the next value
     */
    protected next(): void;
    /**
     * A method to render the prompt
     */
    protected render(): string;
  }
  /**
   * An object representing the configuration options for a toggle prompt, which extends the base PromptFactoryConfig with additional options specific to the toggle prompt.
   */
  export type ToggleConfig = PromptFactoryConfig<boolean> & TogglePromptConfig;
  /**
   * A function to create and run a toggle prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @example
   * ```ts
   * import { toggle, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const likesIceCream = await toggle({
   *     message: "Do you like ice cream?"
   *   });
   *   if (isCancel(likesIceCream)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("You" + (likesIceCream ? " like ice cream" : " don't like ice cream") + "!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the toggle prompt, which
   *   extends the base PromptFactoryConfig with additional options specific to
   *   the toggle prompt
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function toggle(config: ToggleConfig): Promise<boolean | symbol>;
  /**
   * A built-in prompt mask function that masks input with asterisks
   *
   * @param {string} input
   */
  export function passwordMask(input: string): string;
  /**
   * An object representing the configuration options for a password prompt, which extends the base PromptFactoryConfig with additional options specific to password prompts.
   */
  export type PasswordConfig = Omit<TextConfig, "mask" | "maskSubmitted">;
  /**
   * A function to create and run a password prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @remarks
   * This function creates an instance of the TextPrompt class with the provided configuration options and a custom mask function to handle password input. It sets up event listeners for state updates, submission, and cancellation to handle the prompt interactions and return the appropriate results. The password prompt allows users to input text that is masked for privacy, making it suitable for scenarios like entering passwords or sensitive information.
   *
   *
   * @example
   * ```ts
   * import { password, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const userPassword = await password({
   *     message: "Enter your password"
   *   });
   *   if (isCancel(userPassword)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("You entered a password!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the password prompt,
   *   which extends the base PromptConfig with additional options specific to
   *   password prompts
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function password(config: PasswordConfig): Promise<string | symbol>;
  /**
   * Configuration options for creating a boolean confirm prompt
   */
  export interface ConfirmPromptConfig extends PromptConfig<boolean> {
    /**
     * The message for the \`Yes\` state of the prompt
     *
     * @defaultValue "Yes"
     */
    yesMessage?: string;
    /**
     * The \`Yes\` option when choosing between yes/no
     *
     * @defaultValue "1"
     */
    yesOption?: string;
    /**
     * The message for the \`No\` state of the prompt
     *
     * @defaultValue "(Y/n)"
     */
    noMessage?: string;
    /**
     * The \`No\` option when choosing between yes/no
     *
     * @defaultValue "(y/N)"
     */
    noOption?: string;
  }
  /**
   * A prompt for confirming a boolean input
   */
  export class ConfirmPrompt extends Prompt<boolean> {
    protected initialValue: boolean;
    protected yesMessage: string;
    protected yesOption: string;
    protected noMessage: string;
    protected noOption: string;
    protected cursorHidden: boolean;
    constructor(config: ConfirmPromptConfig);
    /**
     * A method to handle keypress events and determine the corresponding action
     *
     * @param char
     * @param key
     */
    protected keypress(char: string, key: readline.Key): any;
    /**
     * A method to render the prompt
     */
    protected render(): string;
  }
  /**
   * An object representing the configuration options for a confirm prompt, which extends the base PromptFactoryConfig with additional options specific to the confirm prompt.
   */
  export type ConfirmConfig = PromptFactoryConfig<boolean> &
    ConfirmPromptConfig;
  /**
   * A function to create and run a confirm prompt, which returns a promise that resolves with the submitted value or rejects with a {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled.
   *
   * @example
   * ```ts
   * import { confirm, isCancel } from "shell-shock:prompts";
   *
   * async function run() {
   *   const likesIceCream = await confirm({
   *     message: "Do you like ice cream?"
   *   });
   *   if (isCancel(likesIceCream)) {
   *     console.log("Prompt was cancelled");
   *     return;
   *   }
   *
   *   console.log("You" + (likesIceCream ? " like ice cream" : " don't like ice cream") + "!");
   * }
   *
   * run();
   * ```
   *
   *
   * @param config - The configuration options to pass to the confirm prompt,
   *   which extends the base PromptFactoryConfig with additional options specific
   *   to the confirm prompt
   * @returns A promise that resolves with the submitted value or rejects with a
   *   {@link CANCEL_SYMBOL | cancel symbol} if the prompt is cancelled
   *
   */
  export function confirm(config: ConfirmConfig): Promise<boolean | symbol>;
  export {};
}
