packages:
  - tools/*
  - packages/*
  - docs/*
  - playground/*

catalog:
  '@alloy-js/core': 0.22.0
  '@alloy-js/markdown': 0.22.0
  '@alloy-js/typescript': ^0.22.0
  '@babel/core': ^7.29.0
  '@eslint/compat': ^2.0.1
  '@eslint/config-inspector': ^1.4.2
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.49.2
  '@nx/devkit': 22.4.1
  '@nx/eslint-plugin': 22.4.1
  '@nx/jest': 22.4.1
  '@nx/js': 22.4.1
  '@nx/plugin': 22.4.1
  '@nx/workspace': 22.4.1
  '@opentui/core': ^0.1.69
  '@opentui/react': ^0.1.69
  '@powerlines/deepkit': ^0.6.43
  '@powerlines/nx': ^0.11.190
  '@powerlines/plugin-alloy': ^0.20.6
  '@powerlines/plugin-automd': ^0.1.263
  '@powerlines/plugin-deepkit': ^0.11.142
  '@powerlines/plugin-env': ^0.15.172
  '@powerlines/plugin-nodejs': ^0.1.167
  '@powerlines/plugin-plugin': ^0.12.214
  '@powerlines/plugin-style-dictionary': ^0.3.164
  '@powerlines/plugin-tsdown': ^0.1.216
  '@powerlines/plugin-tsup': ^0.12.273
  '@powerlines/plugin-untyped': ^0.2.216
  '@powerlines/plugin-vite': ^0.14.264
  '@powerlines/tsconfig': ^0.2.185
  '@storm-software/build-tools': ^0.158.81
  '@storm-software/config': ^1.135.1
  '@storm-software/config-tools': ^1.189.0
  '@storm-software/cspell': ^0.45.75
  '@storm-software/esbuild': ^0.53.81
  '@storm-software/eslint': ^0.169.83
  '@storm-software/git-tools': ^2.124.66
  '@storm-software/linting-tools': ^1.132.81
  '@storm-software/markdownlint': ^0.30.75
  '@storm-software/pnpm-tools': ^0.6.83
  '@storm-software/prettier': ^0.57.80
  '@storm-software/testing-tools': ^1.119.75
  '@storm-software/tsconfig': ^0.47.75
  '@storm-software/tsdoc': ^0.13.75
  '@storm-software/unbuild': ^0.57.81
  '@storm-software/untyped': ^0.24.62
  '@storm-software/workspace-tools': ^1.294.32
  '@stryke/capnp': ^0.12.65
  '@stryke/cli': ^0.13.12
  '@stryke/convert': ^0.6.38
  '@stryke/env': ^0.20.57
  '@stryke/fs': ^0.33.40
  '@stryke/hash': ^0.12.46
  '@stryke/helpers': 0.9.40
  '@stryke/json': ^0.9.41
  '@stryke/path': ^0.26.4
  '@stryke/string-format': ^0.13.7
  '@stryke/type-checks': ^0.5.23
  '@stryke/types': ^0.10.37
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.11
  '@swc/helpers': ^0.5.18
  '@types/eslint': ^9.6.1
  '@types/eslint__js': ^9.14.0
  '@types/jest': ^29.5.14
  '@types/node': ^22.19.7
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/scope-manager': ^8.54.0
  '@typescript-eslint/utils': ^8.54.0
  '@typescript/native-preview': 7.0.0-dev.20251218.3
  automd: 0.4.2
  cfonts: ^3.3.1
  copyfiles: ^2.4.1
  defu: ^6.1.4
  esbuild: ^0.24.2
  eslint: ^9.39.2
  eslint-doc-generator: ^3.0.2
  eslint-flat-config-utils: 2.1.4
  eslint-plugin-eslint-plugin: ^7.3.0
  eslint-plugin-i18n-text: ^1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: ^2.3.0
  globals: ^17.1.0
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  nx: 22.4.1
  powerlines: ^0.38.30
  prettier: ^3.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  rimraf: ^6.1.2
  rolldown: 1.0.0-beta.52
  sherif: ^1.0.0
  style-dictionary: ^5.2.0
  ts-jest: ^29.4.6
  tsup: ^8.3.5
  typescript: ^5.9.3
  unbuild: ^3.3.1
  untyped: ^1.5.2
  verdaccio: ^6.2.5
  vite: ^7.3.0
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.24+sha512-ynYDei9eV8Fakiw0QvhjFE22Y8GMKob331cXfwVc3naxJYXhkjth5PH7E37pQ+jbHmCUVFHQOZU0PxQWkHclmA==

dedupeDirectDeps: true

dedupePeerDependents: true

fetchTimeout: 1000000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - lefthook
  - nx
  - unrs-resolver

overrides:
  '@shell-shock/core': workspace:*
  '@shell-shock/eslint-plugin': workspace:*
  '@shell-shock/nx': workspace:*
  '@shell-shock/plugin-completions': workspace:*
  '@shell-shock/plugin-theme': workspace:*
  '@shell-shock/preset-cli': workspace:*
  '@shell-shock/preset-script': workspace:*
  '@shell-shock/tsconfig': workspace:*
  cookie: '>=0.7.0'
  debug: '>=4.4.0'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.5'
  ip: '>=2.0.1'
  markdown-it: '>=14.1.0'
  micromatch: '>=4.0.8'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  path-to-regexp: '>=0.1.12'
  postcss: '>=8.5.1'
  shell-quote: '>=1.8.2'
  simple-git: '>=3.27.0'

shamefullyHoist: true

useNodeVersion: 24.11.1
