packages:
  - tools/*
  - packages/*
  - docs/*
  - playground/*
catalog:
  "@alloy-js/core": 0.23.0-dev.8
  "@alloy-js/json": 0.23.0-dev.2
  "@alloy-js/markdown": 0.23.0-dev.1
  "@alloy-js/typescript": 0.23.0-dev.4
  "@babel/core": ^7.29.0
  "@eslint/compat": ^2.0.1
  "@eslint/config-inspector": ^1.4.2
  "@ls-lint/ls-lint": ^2.3.1
  "@microsoft/api-extractor": ^7.49.2
  "@nx/devkit": 22.5.2
  "@nx/eslint-plugin": 22.5.2
  "@nx/jest": 22.5.2
  "@nx/js": 22.5.2
  "@nx/plugin": 22.5.2
  "@nx/workspace": 22.5.2
  "@powerlines/deepkit": ^0.6.69
  "@powerlines/nx": ^0.11.216
  "@powerlines/plugin-alloy": ^0.23.19
  "@powerlines/plugin-automd": ^0.1.289
  "@powerlines/plugin-deepkit": ^0.11.168
  "@powerlines/plugin-env": ^0.16.6
  "@powerlines/plugin-nodejs": ^0.1.207
  "@powerlines/plugin-plugin": ^0.12.240
  "@powerlines/plugin-style-dictionary": ^0.3.190
  "@powerlines/plugin-tsdown": ^0.1.242
  "@powerlines/plugin-tsup": ^0.12.299
  "@powerlines/plugin-untyped": ^0.2.242
  "@powerlines/plugin-vite": ^0.14.291
  "@powerlines/tsconfig": ^0.2.211
  "@storm-software/build-tools": ^0.158.90
  "@storm-software/config": ^1.135.10
  "@storm-software/config-tools": ^1.189.9
  "@storm-software/cspell": ^0.45.86
  "@storm-software/esbuild": ^0.53.91
  "@storm-software/eslint": ^0.169.95
  "@storm-software/git-tools": ^2.124.76
  "@storm-software/linting-tools": ^1.132.93
  "@storm-software/markdownlint": ^0.30.84
  "@storm-software/pnpm-tools": ^0.6.93
  "@storm-software/prettier": ^0.58.8
  "@storm-software/testing-tools": ^1.119.84
  "@storm-software/tsconfig": ^0.47.84
  "@storm-software/tsdoc": ^0.13.84
  "@storm-software/unbuild": ^0.57.91
  "@storm-software/untyped": ^0.24.72
  "@storm-software/workspace-tools": ^1.294.42
  "@stryke/capnp": ^0.12.68
  "@stryke/cli": ^0.13.15
  "@stryke/convert": ^0.6.40
  "@stryke/env": ^0.20.60
  "@stryke/fs": ^0.33.43
  "@stryke/hash": ^0.12.49
  "@stryke/helpers": ^0.9.42
  "@stryke/json": ^0.9.43
  "@stryke/path": 0.26.6
  "@stryke/string-format": 0.14.2
  "@stryke/type-checks": ^0.5.25
  "@stryke/types": ^0.10.39
  "@swc-node/register": 1.11.1
  "@swc/core": 1.15.8
  "@swc/helpers": 0.5.18
  "@types/eslint": ^9.6.1
  "@types/eslint__js": ^9.14.0
  "@types/jest": ^29.5.14
  "@types/node": ^25.3.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/scope-manager": ^8.54.0
  "@typescript-eslint/utils": ^8.56.1
  "@typescript/native-preview": 7.0.0-dev.20251218.3
  automd: ^0.4.3
  cfonts: ^3.3.1
  copyfiles: ^2.4.1
  defu: 6.1.4
  didyoumean2: ^7.0.4
  esbuild: ^0.24.2
  eslint: ^9.39.3
  eslint-doc-generator: ^3.2.0
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-eslint-plugin: ^7.3.1
  eslint-plugin-i18n-text: ^1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: ^2.3.1
  globals: ^17.1.0
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  nx: 22.5.2
  powerlines: ^0.38.56
  prettier: ^3.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  rimraf: ^6.1.3
  rolldown: 1.0.0-beta.52
  sherif: ^1.0.0
  style-dictionary: ^5.3.2
  ts-jest: ^29.4.6
  tsup: ^8.3.5
  typescript: ^5.9.3
  unbuild: ^3.3.1
  untyped: ^1.5.2
  verdaccio: ^6.2.7
  vite: ^7.3.0
  zx: ^8.8.5
configDependencies:
  pnpm-plugin-storm-software: 0.1.24+sha512-ynYDei9eV8Fakiw0QvhjFE22Y8GMKob331cXfwVc3naxJYXhkjth5PH7E37pQ+jbHmCUVFHQOZU0PxQWkHclmA==
dedupeDirectDeps: true
dedupePeerDependents: true
fetchTimeout: 1000000
minimumReleaseAgeExclude:
  - "@storm-software/*"
  - "@stryke/*"
  - "@powerlines/*"
  - powerlines
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - esbuild
  - lefthook
  - nx
  - unrs-resolver
overrides:
  "@shell-shock/core": workspace:*
  "@shell-shock/eslint-plugin": workspace:*
  "@shell-shock/nx": workspace:*
  "@shell-shock/plugin-completions": workspace:*
  "@shell-shock/plugin-console": workspace:*
  "@shell-shock/plugin-prompts": workspace:*
  "@shell-shock/plugin-theme": workspace:*
  "@shell-shock/plugin-upgrade": workspace:*
  "@shell-shock/preset-cli": workspace:*
  "@shell-shock/preset-script": workspace:*
  "@shell-shock/tsconfig": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
shamefullyHoist: true
useNodeVersion: 25.5.0
