packages:
  - tools/*
  - packages/*
  - docs/*
  - playground/*

catalog:
  '@alloy-js/core': 0.23.0-dev.8
  '@alloy-js/markdown': 0.23.0-dev.1
  '@alloy-js/typescript': 0.23.0-dev.4
  '@eslint/compat': ^2.0.5
  '@eslint/config-inspector': ^1.5.0
  '@ls-lint/ls-lint': ^2.3.1
  '@mdit/plugin-alert': ^0.23.2
  '@nx/devkit': 22.7.0
  '@nx/eslint-plugin': 22.7.0
  '@nx/jest': 22.7.0
  '@nx/js': 22.7.0
  '@nx/plugin': 22.7.0
  '@nx/workspace': 22.7.0
  '@powerlines/deepkit': ^0.8.49
  '@powerlines/nx': ^0.13.22
  '@powerlines/plugin-alloy': ^0.26.67
  '@powerlines/plugin-automd': ^0.1.448
  '@powerlines/plugin-deepkit': ^0.11.330
  '@powerlines/plugin-nodejs': ^0.1.375
  '@powerlines/plugin-plugin': ^0.12.399
  '@powerlines/plugin-style-dictionary': ^0.3.349
  '@powerlines/plugin-tsdown': ^0.1.389
  '@powerlines/plugin-untyped': ^0.2.402
  '@powerlines/tsconfig': ^0.4.85
  '@powerlines/tsdoc': ^0.2.33
  '@standard-schema/spec': ^1.1.0
  '@standard-schema/utils': ^0.3.0
  '@storm-software/config': ^1.137.34
  '@storm-software/config-tools': ^1.190.1
  '@storm-software/cspell': ^0.46.70
  '@storm-software/eslint': ^0.170.22
  '@storm-software/git-tools': ^2.130.39
  '@storm-software/linting-tools': ^1.133.31
  '@storm-software/markdownlint': ^0.30.158
  '@storm-software/pnpm-tools': ^0.7.10
  '@storm-software/prettier': ^0.59.54
  '@storm-software/testing-tools': ^1.119.155
  '@storm-software/tsconfig': ^0.48.69
  '@storm-software/untyped': ^0.24.143
  '@storm-software/workspace-tools': ^1.295.60
  '@stryke/cli': ^0.13.41
  '@stryke/convert': ^0.7.2
  '@stryke/fs': ^0.33.69
  '@stryke/hash': ^0.13.22
  '@stryke/helpers': ^0.10.11
  '@stryke/json': ^0.14.15
  '@stryke/path': ^0.28.1
  '@stryke/string-format': ^0.17.12
  '@stryke/type-checks': ^0.6.4
  '@stryke/types': ^0.11.6
  '@stryke/zod': ^0.3.16
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.32
  '@swc/helpers': ^0.5.21
  '@types/eslint': ^9.6.1
  '@types/eslint__js': ^9.14.0
  '@types/jest': ^29.5.14
  '@types/json-schema': ^7.0.15
  '@types/node': ^25.6.0
  '@typescript-eslint/utils': ^8.59.1
  '@typescript/native-preview': 7.0.0-dev.20251218.3
  automd: ^0.4.3
  cfonts: ^3.3.1
  chalk-string: ^4.0.0
  copyfiles: ^2.4.1
  defu: ^6.1.7
  esbuild: ^0.24.2
  eslint: ^9.39.4
  eslint-doc-generator: ^3.3.2
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-eslint-plugin: ^7.3.2
  eslint-plugin-i18n-text: ^1.0.1
  eslint-rule-documentation: ^1.0.23
  eslint-typegen: ^2.3.1
  he: ^1.2.0
  jest: ^30.3.0
  jest-environment-jsdom: ^30.3.0
  jest-environment-node: ^30.3.0
  jiti: ^2.6.1
  json-schema: ^0.4.0
  jsonc-eslint-parser: ^2.4.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  markdown-it: ^14.1.1
  markdown-it-abbr: ^2.0.0
  markdown-it-container: ^4.0.0
  markdown-it-deflist: ^3.0.0
  markdown-it-footnote: ^4.0.0
  markdown-it-ins: ^4.0.0
  markdown-it-mark: ^4.0.0
  markdown-it-sub: ^2.0.0
  markdown-it-sup: ^2.0.0
  markdown-it-task-lists: ^2.1.1
  normalize-html-whitespace: ^1.0.0
  nx: 22.7.0
  parse5: ^8.0.1
  powerlines: ^0.44.12
  prettier: ^3.8.3
  rimraf: ^6.1.3
  style-dictionary: ^5.4.0
  terminal-size: ^4.0.1
  ts-jest: ^29.4.9
  tsdown: ^0.21.10
  typescript: ^6.0.3
  untyped: ^1.5.2
  verdaccio: 6.5.0
  wrap-ansi: ^10.0.0
  zod: ^4.3.6
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.113+sha512-8d/REhdMgHZqzrnTgRZ4I+g9WNnNMkPniuUzMHtMbGX0gGoduFK7+2buTlLjXEXGSXPhrcVhh5n87Sae1Hg4Iw==

dedupeDirectDeps: true

dedupePeerDependents: true

fetchTimeout: 1000000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - lefthook
  - nx
  - unrs-resolver

overrides:
  '@babel/core': 8.0.0-rc.3
  '@babel/preset-typescript': 8.0.0-rc.3
  '@shell-shock-playground/cli': workspace:*
  '@shell-shock-playground/custom-commands-directory': workspace:*
  '@shell-shock-playground/minimal': workspace:*
  '@shell-shock-playground/nx': workspace:*
  '@shell-shock-playground/powerlines': workspace:*
  '@shell-shock-playground/script': workspace:*
  '@shell-shock/core': workspace:*
  '@shell-shock/eslint-plugin': workspace:*
  '@shell-shock/nx': workspace:*
  '@shell-shock/plugin-banner': workspace:*
  '@shell-shock/plugin-changelog': workspace:*
  '@shell-shock/plugin-completions': workspace:*
  '@shell-shock/plugin-console': workspace:*
  '@shell-shock/plugin-help': workspace:*
  '@shell-shock/plugin-prompts': workspace:*
  '@shell-shock/plugin-theme': workspace:*
  '@shell-shock/plugin-upgrade': workspace:*
  '@shell-shock/preset-cli': workspace:*
  '@shell-shock/preset-script': workspace:*
  '@shell-shock/tsconfig': workspace:*
  '@shell-shock/unified': workspace:*
  cookie: '>=0.7.0'
  debug: '>=4.4.0'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.5'
  ip: '>=2.0.1'
  micromatch: '>=4.0.8'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  path-to-regexp: '>=0.1.12'
  postcss: '>=8.5.1'
  shell-quote: '>=1.8.2'
  simple-git: '>=3.27.0'

shamefullyHoist: true

useNodeVersion: 25.5.0
