/**
 * A collection of helper utilities that ease command-line application development.
 *
 * @module powerlines:utils
 */

/* eslint-disable */
// biome-ignore lint: disable

import { os } from "node:os";
import { process } from "node:process";

// Generated byPowerlines
// NOTE: Do not edit this file manually - it will be overwritten automatically
// by the "prepare" command

/**
 * Checks if a specific flag is present in the command line arguments.
 *
 * @see https://github.com/sindresorhus/has-flag/blob/main/index.js
 *
 * @param flag - The flag (or an array of flags/aliases) to check for, e.g.,
 *   "color", "no-color".
 * @param argv - The command line arguments to check against. Defaults to global
 *   Deno args or process args.
 * @returns True if the flag is present, false otherwise.
 *
 */
export function hasFlag(
  flag: string | string[],
  argv?: string[] = globalThis.Deno ? globalThis.Deno.args : process.argv
) {
  const position: number = (Array.isArray(flag) ? flag : [flag]).reduce(
    (ret, f) => {
      const pos = argv.findIndex(
        arg =>
          (f.startsWith("-")
            ? ""
            : (f.length === 1 ? "-" : "--") + f
          )?.toLowerCase() === arg?.toLowerCase() ||
          arg
            ?.toLowerCase()
            .startsWith((f.length === 1 ? "-" : "--") + f + "=")
            ?.toLowerCase()
      );
      return pos !== -1 ? pos : ret;
    },
    -1
  );
  return (
    (position !== -1 && argv.indexOf("--") === -1) ||
    position < argv.indexOf("--")
  );
}

/**
 * Detect if stdout.TTY is available
 */
export const isTTY = Boolean(process.stdout && process.stdout.isTTY);

/**
 * Detect if the current environment is minimal (CI, non-TTY, etc.)
 */
export const isMinimal = env.MINIMAL || isCI || isTest || !isTTY;

/**
 * Detect if the current environment is interactive
 */
export const isInteractive =
  !isMinimal && process.stdin?.isTTY && env.TERM !== "dumb";

function parseVersion(version: string = "") {
  if (/^d{3,4}$/.test(version)) {
    const match = /(d{1,2})(d{2})/.exec(version) ?? [];

    return {
      major: 0,
      minor: Number.parseInt(match[1]!, 10),
      patch: Number.parseInt(match[2]!, 10)
    };
  }

  const versionParts = (version ?? "")
    .split(".")
    .map(n => Number.parseInt(n, 10));

  return {
    major: versionParts[0],
    minor: versionParts[1],
    patch: versionParts[2]
  };
} /**
 * Check if the current environment/terminal supports hyperlinks in the terminal.
 *
 * @returns True if the current environment/terminal supports hyperlinks.
 *
 */
export function isHyperlinkSupported(): boolean {
  if (Boolean(env.FORCE_HYPERLINK)) {
    return true;
  }

  if (Boolean(env.NETLIFY)) {
    return true;
  } else if (isColorSupported || isTTY) {
    return false;
  } else if (Boolean(env.WT_SESSION)) {
    return true;
  } else if (isWindows || isMinimal || Boolean(env.TEAMCITY_VERSION)) {
    return false;
  } else if (Boolean(env.TERM_PROGRAM)) {
    const version = parseVersion(env.TERM_PROGRAM_VERSION);

    switch (String(env.TERM_PROGRAM)) {
      case "iTerm.app": {
        if (version.major === 3) {
          return version.minor !== undefined && version.minor >= 1;
        }

        return version.major !== undefined && version.major > 3;
      }
      case "WezTerm": {
        return version.major !== undefined && version.major >= 20_200_620;
      }

      case "vscode": {
        if (Boolean(env.CURSOR_TRACE_ID)) {
          return true;
        }

        return (
          version.minor !== undefined &&
          version.major !== undefined &&
          (version.major > 1 || (version.major === 1 && version.minor >= 72))
        );
      }

      case "ghostty": {
        return true;
      }
    }
  }

  if (Boolean(env.VTE_VERSION)) {
    if (env.VTE_VERSION === "0.50.0") {
      return false;
    }

    const version = parseVersion(env.VTE_VERSION);
    return (
      (version.major !== undefined && version.major > 0) ||
      (version.minor !== undefined && version.minor >= 50)
    );
  }

  if (String(env.TERM) === "alacritty") {
    return true;
  }

  return false;
}

/**
 * Options for the getColorSupportLevel function
 */
export interface GetColorSupportLevelOptions {
  /**
   * Indicates if the function should skip checking command-line flags for color support
   */
  ignoreFlags: boolean;
}

/**
 * Checks if a specific flag is present in the command line arguments.
 *
 * @see https://github.com/sindresorhus/has-flag/blob/main/index.js
 *
 * @param flag - The flag to check for, e.g., "color", "no-color".
 * @param argv - The command line arguments to check against. Defaults to global
 *   Deno args or process args.
 * @returns True if the flag is present, false otherwise.
 *
 */
export function getColorSupportLevel(
  stream: NodeJS.WriteStream & { fd: 1 | 2 },
  options: GetColorSupportLevelOptions = {}
) {
  const { ignoreFlags = false } = options;

  let forceColor: number | undefined;
  if (env.FORCE_COLOR !== undefined) {
    forceColor = !env.FORCE_COLOR
      ? 0
      : typeof env.FORCE_COLOR === "boolean"
        ? 1
        : typeof env.FORCE_COLOR === "number" &&
            [0, 1, 2, 3].includes(Math.min(env.FORCE_COLOR as number, 3))
          ? Math.min(env.FORCE_COLOR as number, 3)
          : undefined;
  }

  if (ignoreFlags !== true && forceColor === undefined) {
    forceColor =
      hasFlag("no-color") ||
      hasFlag("no-colors") ||
      hasFlag("color=false") ||
      hasFlag("color=never")
        ? 0
        : hasFlag("color") ||
            hasFlag("colors") ||
            hasFlag("color=true") ||
            hasFlag("color=always")
          ? 1
          : 0;
  }

  if (forceColor === 0) {
    return 0;
  }

  if (ignoreFlags !== true) {
    if (
      hasFlag("color=16m") ||
      hasFlag("color=full") ||
      hasFlag("color=truecolor")
    ) {
      return 3;
    }

    if (hasFlag("color=256")) {
      return 2;
    }
  }

  const level =
    Boolean(env.TF_BUILD) || Boolean(env.AGENT_NAME)
      ? 1
      : stream &&
          !(isTTY || (stream && stream.isTTY)) &&
          forceColor === undefined
        ? 0
        : env.TERM === "dumb"
          ? forceColor || 0
          : isWindows
            ? Number(os.release().split(".")[0]) >= 10 &&
              Number(os.release().split(".")[2]) >= 10_586
              ? Number(os.release().split(".")[2]) >= 14_931
                ? 3
                : 2
              : 1
            : isCI
              ? Boolean(env.GITHUB_ACTIONS) ||
                Boolean(env.GITEA_ACTIONS) ||
                Boolean(env.CIRCLECI)
                ? 3
                : Boolean(env.TRAVIS) ||
                    Boolean(env.APPVEYOR) ||
                    Boolean(env.GITLAB_CI) ||
                    Boolean(env.BUILDKITE) ||
                    Boolean(env.DRONE) ||
                    env.CI_NAME === "codeship"
                  ? 1
                  : forceColor || 0
              : Boolean(env.TEAMCITY_VERSION)
                ? /^(?:9.0*[1-9]d*.|d{2,}.)/.test(
                    String(env.TEAMCITY_VERSION) || ""
                  )
                  ? 1
                  : 0
                : String(env.COLORTERM) === "truecolor" ||
                    env.TERM === "xterm-kitty"
                  ? 3
                  : Boolean(env.TERM_PROGRAM)
                    ? env.TERM_PROGRAM === "iTerm.app"
                      ? Number.parseInt(
                          (env.TERM_PROGRAM_VERSION || "").split(
                            "."
                          )[0] as string,
                          10
                        ) >= 3
                        ? 3
                        : 2
                      : env.TERM_PROGRAM === "Apple_Terminal"
                        ? 2
                        : 0
                    : /-256(?:color)?$/i.test(env.TERM || "")
                      ? 2
                      : /^screen|^xterm|^vt100|^vt220|^rxvt|color|ansi|cygwin|linux/i.test(
                            env.TERM || ""
                          )
                        ? 1
                        : Boolean(env.COLORTERM);

  return typeof level === "boolean" || level === 0
    ? false
    : {
        level,
        hasBasic: true,
        has256: level >= 2,
        has16m: level >= 3
      };
}

/**
 * Detect the terminal color support level in the current environment
 */
export const colorSupportLevels = {
  stdout: getColorSupportLevel(process.stdout),
  stderr: getColorSupportLevel(process.stderr)
};

/**
 * Detect if terminal color is supported in the current environment
 */
export const isColorSupported = Boolean(colorSupportLevels.stdout);

/**
 * Detect if Unicode characters are supported in the current environment
 */
export const isUnicodeSupported = !isWindows
  ? env.TERM !== "linux"
  : Boolean(env.WT_SESSION) ||
    Boolean(env.TERMINUS_SUBLIME) ||
    env.ConEmuTask === "{cmd::Cmder}" ||
    env.TERM_PROGRAM === "Terminus-Sublime" ||
    env.TERM_PROGRAM === "vscode" ||
    env.TERM === "xterm-256color" ||
    env.TERM === "alacritty" ||
    env.TERM === "rxvt-unicode" ||
    env.TERM === "rxvt-unicode-256color" ||
    env.TERMINAL_EMULATOR === "JetBrains-JediTerm";
