/* eslint-disable */
// biome-ignore lint: disable

// Generated with Powerlines
// Note: Do not edit this file manually - it will be overwritten automatically

declare module "powerlines:utils" {}

declare module "powerlines:console" {}
