/* eslint-disable */
// biome-ignore lint: disable

// Generated with Shell Shock
// Note: Do not edit this file manually - it will be overwritten automatically

/**
 * The environment configuration module provides an interface to define environment configuration parameters.
 *
 * @module shell-shock:env
 */
declare module "shell-shock:env" {
  /**
   * Object
   *
   * @title Object
   *
   */
  export interface EnvBase {
    /**
     * The application's cached data directory.
     *
     * @title Cache Directory
     *
     */
    CACHE_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a continuous integration environment.
     *
     * @title Continuous Integration
     * @alias CONTINUOUS_INTEGRATION
     * @defaultValue false
     *
     */
    CI: boolean;
    /**
     * The application's configuration data directory.
     *
     * @title Configuration Directory
     *
     */
    CONFIG_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a continuous integration environment.
     *
     * @title Continuous Integration
     * @alias CI
     * @defaultValue false
     *
     */
    CONTINUOUS_INTEGRATION: boolean;
    /**
     * The application's runtime data directory.
     *
     * @title Data Directory
     *
     */
    DATA_DIR?: string;
    /**
     * Indicates if the application is running in debug mode.
     *
     * @defaultValue true
     *
     */
    DEBUG: boolean;
    /**
     * The default locale to be used in the application.
     *
     * @defaultValue "en-US"
     *
     */
    DEFAULT_LOCALE: string;
    /**
     * The default timezone for the application.
     *
     * @defaultValue "America/New_York"
     *
     */
    DEFAULT_TIMEZONE: string;
    /**
     * A variable that specifies the [Devenv](https://devenv.sh/) runtime directory.
     *
     * @defaultValue "/run/user/1001/devenv-22d1a8e"
     *
     */
    DEVENV_RUNTIME?: string;
    /**
     * The environment the application is running in. This value will be populated with the value of `MODE` if not provided.
     *
     * @defaultValue "development"
     *
     */
    ENVIRONMENT: string;
    /**
     * A web page to lookup error messages and display additional information given an error code.
     *
     * @title Error Details URL
     * @defaultValue "https://developer.stormsoftware.com/static/errors"
     *
     */
    ERROR_URL: string;
    /**
     * An indicator that specifies the current runtime is a force color environment.
     *
     * @defaultValue true
     *
     */
    FORCE_COLOR: boolean | number;
    /**
     * An indicator that specifies the current runtime should force hyperlinks in terminal output.
     *
     * @defaultValue false
     *
     */
    FORCE_HYPERLINK: boolean | number;
    /**
     * Indicates if error data should be included.
     *
     * @defaultValue false
     *
     */
    INCLUDE_ERROR_DATA: boolean;
    /**
     * The application's logging directory.
     *
     * @title Log Directory
     *
     */
    LOG_DIR?: string;
    /**
     * The default lowest log level to accept. If `null`, the logger will reject all records.
     *
     * @defaultValue "debug"
     *
     */
    LOG_LEVEL?: "error" | "warn" | "info" | "debug" | null;
    /**
     * An indicator that specifies the current runtime is a minimal environment.
     *
     * @defaultValue false
     *
     */
    MINIMAL: boolean;
    /**
     * The mode in which the application is running.
     *
     * @alias NODE_ENV
     *
     * @alias VERCEL_ENV
     * @defaultValue "development"
     *
     */
    MODE: "development" | "test" | "production";
    /**
     * An indicator that specifies the current runtime is a no color environment.
     *
     * @defaultValue false
     *
     */
    NO_COLOR: boolean;
    /**
     * The mode in which the application is running.
     *
     * @title Mode
     * @alias VERCEL_ENV
     *
     * @alias MODE
     * @defaultValue "development"
     *
     */
    NODE_ENV: "development" | "test" | "production";
    /**
     * The name of the organization that maintains the application.
     *
     * @title Organization
     * @alias ORGANIZATION
     * @defaultValue "storm-software"
     *
     */
    ORG: string;
    /**
     * The name of the organization that maintains the application.
     *
     * @alias ORG
     * @defaultValue "storm-software"
     *
     */
    ORGANIZATION: string;
    /**
     * The platform for which the application was built.
     *
     * @defaultValue "node"
     *
     */
    PLATFORM: "node" | "neutral" | "browser";
    /**
     * Indicates if error stack traces should be captured.
     *
     * @defaultValue true
     *
     */
    STACKTRACE: boolean;
    /**
     * The application's temporary data directory.
     *
     * @title Temporary Directory
     *
     */
    TEMP_DIR?: string;
    /**
     * An indicator that specifies the current runtime is a test environment.
     *
     * @defaultValue false
     *
     */
    TEST: boolean;
    /**
     * The mode in which the application is running.
     *
     * @title Mode
     * @alias NODE_ENV
     *
     * @alias MODE
     * @defaultValue "production"
     *
     */
    VERCEL_ENV: "development" | "test" | "production";
    /**
     * The appcircle build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AC_APPCIRCLE?: string;
    /**
     * The name of the agent running the application. This variable is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AGENT_NAME?: string;
    /**
     * The agola git reference. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly AGOLA_GIT_REF?: string;
    /**
     * The name of the application.
     *
     * @readonly
     * @defaultValue "playground-complex"
     *
     */
    readonly APP_NAME: string;
    /**
     * The version of the application.
     *
     * @readonly
     * @defaultValue "0.0.1"
     *
     */
    readonly APP_VERSION: string;
    /**
     * The appcenter build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly APPCENTER_BUILD_ID?: string;
    /**
     * A variable that specifies the application data directory on Windows.
     *
     * @readonly
     *
     */
    readonly APPDATA?: string;
    /**
     * The appveyor build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly APPVEYOR?: string;
    /**
     * The bamboo plan key. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly bamboo_planKey?: string;
    /**
     * The bitbucket commit. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BITBUCKET_COMMIT?: string;
    /**
     * The bitrise build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BITRISE_IO?: string;
    /**
     * The buddy workspace ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUDDY_WORKSPACE_ID?: string;
    /**
     * A checksum hash created during the build.
     *
     * @readonly
     * @defaultValue "VTEIubSVzmhcPC4RTI012CoaJwOJJD6g"
     *
     */
    readonly BUILD_CHECKSUM: string;
    /**
     * The unique identifier for the build.
     *
     * @readonly
     * @defaultValue "2ed488bf-f757-4403-8985-d1cb155c53be"
     *
     */
    readonly BUILD_ID: string;
    /**
     * The timestamp the build was ran at.
     *
     * @readonly
     * @defaultValue "2026-01-25T09:06:20.072Z"
     *
     */
    readonly BUILD_TIMESTAMP: string;
    /**
     * The builder output build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUILDER_OUTPUT?: string;
    /**
     * The buildkite build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly BUILDKITE?: string;
    /**
     * The cf build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CF_BUILD_ID?: string;
    /**
     * The ci name. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CI_NAME?: string;
    /**
     * The xcode project build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CI_XCODE_PROJECT?: string;
    /**
     * The circleci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CIRCLECI?: string;
    /**
     * The cirrus-ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CIRRUS_CI?: string;
    /**
     * The cm build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CM_BUILD_ID?: string;
    /**
     * The codebuild build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly CODEBUILD?: string;
    /**
     * The color terminal type. This variable is set by certain terminal emulators.
     *
     * @readonly
     * @defaultValue "truecolor"
     *
     */
    readonly COLORTERM?: string;
    /**
     * The ConEmu task name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly ConEmuTask?: string;
    /**
     * The cursor trace ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly CURSOR_TRACE_ID?: string;
    /**
     * The drone build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly DRONE?: string;
    /**
     * The dsari build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly DSARI?: string;
    /**
     * The earthly build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly EARTHLY_CI?: string;
    /**
     * The eas build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly EAS_BUILD?: string;
    /**
     * The gerrit project. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GERRIT_PROJECT?: string;
    /**
     * The gitea actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITEA_ACTIONS?: string;
    /**
     * The github actions build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITHUB_ACTIONS?: string;
    /**
     * The gitlab ci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GITLAB_CI?: string;
    /**
     * The go cd build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly GOCD?: string;
    /**
     * The harness build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly HARNESS_BUILD_ID?: string;
    /**
     * The hudson build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly HUDSON?: string;
    /**
     * The jenkins url. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly JENKINS_URL?: string;
    /**
     * The layerci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly LAYERCI?: string;
    /**
     * A variable that specifies the current user's local application data directory on Windows.
     *
     * @readonly
     *
     */
    readonly LOCALAPPDATA?: string;
    /**
     * The magnum build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly MAGNUM?: string;
    /**
     * The netlify build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NETLIFY?: string;
    /**
     * The nevercode build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NEVERCODE?: string;
    /**
     * The now builder build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly NOW_BUILDER?: string;
    /**
     * The prow job ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly PROW_JOB_ID?: string;
    /**
     * The release build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RELEASE_BUILD_ID?: string;
    /**
     * The unique identifier for the release.
     *
     * @readonly
     * @defaultValue "d488bff7-5724-4309-85d1-cb155c53befe"
     *
     */
    readonly RELEASE_ID: string;
    /**
     * The tag for the release. This is generally in the format of "\<APP_NAME\>\@\<APP_VERSION\>".
     *
     * @readonly
     * @defaultValue "playground-complex@0.0.1"
     *
     */
    readonly RELEASE_TAG: string;
    /**
     * The render build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RENDER?: string;
    /**
     * The unique identifier for the current run. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly RUN_ID?: string;
    /**
     * The sailci build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SAILCI?: string;
    /**
     * The screwdriver build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SCREWDRIVER?: string;
    /**
     * The semaphore build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SEMAPHORE?: string;
    /**
     * The sourcehut build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SOURCEHUT?: string;
    /**
     * The spaceship build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly SPACESHIP_CI?: string;
    /**
     * The strider build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly STRIDER?: string;
    /**
     * The task ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TASK_ID?: string;
    /**
     * The teamcity version. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TEAMCITY_VERSION?: string;
    /**
     * The terminal type. This variable is set by certain CI/CD systems.
     *
     * @readonly
     * @defaultValue "xterm-256color"
     *
     */
    readonly TERM?: string;
    /**
     * The terminal program name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERM_PROGRAM?: string;
    /**
     * The terminal program version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERM_PROGRAM_VERSION?: string;
    /**
     * The terminal emulator name. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERMINAL_EMULATOR?: string;
    /**
     * An indicator that specifies the current terminal is running Terminus Sublime. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly TERMINUS_SUBLIME?: boolean;
    /**
     * The task force build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TF_BUILD?: string;
    /**
     * The travis build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly TRAVIS?: string;
    /**
     * The vela build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly VELA?: string;
    /**
     * The VTE version. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly VTE_VERSION?: string;
    /**
     * The terminal emulator session ID. This variable is set by certain terminal emulators.
     *
     * @readonly
     *
     */
    readonly WT_SESSION?: string;
    /**
     * The xcode server build ID. This value is set by certain CI/CD systems.
     *
     * @readonly
     *
     */
    readonly XCS?: string;
    /**
     * A variable that specifies the cache path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_CACHE_HOME?: string;
    /**
     * A variable that specifies the configuration path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_CONFIG_HOME?: string;
    /**
     * A variable that specifies the data path in the home directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_DATA_HOME?: string;
    /**
     * A variable that specifies the runtime directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     * @defaultValue "/run/user/1001"
     *
     */
    readonly XDG_RUNTIME_DIR?: string;
    /**
     * A variable that specifies the state directory on Linux systems using the XDG base directory specification.
     *
     * @readonly
     *
     */
    readonly XDG_STATE_HOME?: string;
  }
  /**
   * The environment configuration object with prefixed keys.
   *
   * @remarks
   * The `Env` type extends the `EnvBase` interface by including additional keys that are prefixed according to the project's configuration. This allows for flexibility in accessing environment variables with different naming conventions.
   */
  export type Env = {
    [Key in keyof EnvBase as
      | Key
      | `NEXT_${Key}`
      | `ONE_${Key}`
      | `PLAYGROUND_COMPLEX_${Key}`
      | `POWERLINES_${Key}`
      | `SHELL_SHOCK_${Key}`
      | `STORM_STACK_${Key}`
      | `STORM_${Key}`
      | `VERCEL_${Key}`
      | `VITE_${Key}`]: EnvBase[Key];
  };
  /**
   * The initial environment configuration state for the Playground Complex project.
   *
   * @title Object
   *
   */
  export const initialEnv: Partial<EnvBase>;
  /**
   * The environment configuration serializer for the Powerlines application.
   *
   * @see https://deepkit.io/docs/serialization/serializers
   *
   * @see https://github.com/marcj/untitled-code/blob/master/packages/type/src/serializer.ts#L1918
   *
   * @remarks
   * This serializer is used to serialize and deserialize the Powerlines environment configuration.
   */
  export class EnvSerializer extends Serializer {
    /**
     * Initializes a new instance of the `EnvSerializer` class.
     */
    constructor();
  }
  /**
   * Serialize a environment configuration object to JSON data objects (not a JSON string).
   *
   * @remarks
   * The resulting JSON object can be stringified using `JSON.stringify()`.
   * @example
   * ```ts
   * const json = serializeEnv(env);
   * ```
   * @throws ValidationError when serialization or validation fails.
   *
   */
  export const serializeEnv: import("@powerlines/deepkit/vendor/type").SerializeFunction<
    EnvBase,
    any
  >;
  /**
   * Deserialize a environment configuration object from JSON data objects to JavaScript objects, without running any validators.
   *
   * @remarks
   * Types that are already correct will be used as-is.
   * @example
   * ```ts
   * const env = deserializeEnv(json);
   * ```
   * @throws ValidationError when deserialization fails.
   *
   */
  export const deserializeEnv: import("@powerlines/deepkit/vendor/type").SerializeFunction<
    any,
    EnvBase
  >;
  /**
   * Initializes the Powerlines environment configuration module.
   *
   * @remarks
   * This function initializes the Powerlines environment configuration object.
   * @param environmentConfig - The dynamic/runtime configuration - this could
   *   include the current environment variables or any other environment-specific
   *   settings provided by the runtime.
   * @returns The initialized Powerlines configuration object.
   *
   */
  export function createEnv(environmentConfig?: Partial<Env>): Env;
  /**
   * The environment configuration object.
   *
   * @remarks
   * This object provides access to the environment configuration parameters in the application runtime.
   */
  export const env: Env;
  /**
   * Detect if the application is running in a continuous integration (CI) environment.
   */
  export const isCI: boolean;
  /**
   * Detect the \`mode\` of the current runtime environment.
   *
   * @remarks
   * The `mode` is determined by the `MODE` environment variable, or falls back to the `NEXT_PUBLIC_VERCEL_ENV`, `NODE_ENV`, or defaults to `production`. While the value can potentially be any string, it is generally recommended to only allow a value in the following list:
   *
   * - `production`
   *
   * - `test`
   *
   * - `development`
   */
  export const mode: string;
  /**
   * Detect if the application is running in `"production"` mode
   */
  export const isProduction: boolean;
  /**
   * Detect if the application is running in `"test"` mode
   */
  export const isTest: boolean;
  /**
   * Detect if the application is running in `"development"` mode
   */
  export const isDevelopment: boolean;
  /**
   * Detect if the application is currently being debugged
   */
  export const isDebug: boolean;
  /**
   * An indicator specifying whether the current operating system is MacOS (darwin kernel).
   */
  export const isWindows: boolean;
  /**
   * An indicator specifying whether the current operating system is Linux.
   */
  export const isLinux: boolean;
  /**
   * An indicator specifying whether the current operating system is MacOS (darwin kernel).
   */
  export const isMacOS: boolean;
  /**
   * The environment path types for storing things like data, config, logs, and cache in the current runtime environment.
   *
   * @remarks
   * These environment path types are accessed in the {@link EnvPaths} type.
   */
  export type EnvPathType = "data" | "config" | "cache" | "log" | "temp";
  /**
   * The environment paths for storing things like data, config, logs, and cache in the current runtime environment.
   *
   */
  export type EnvPaths = Record<EnvPathType, string>;
  /**
   * The resolved application directories based on the current operating system and environment variables.
   *
   * @remarks
   * If the `DATA_DIR`, `CONFIG_DIR`, `CACHE_DIR`, `LOG_DIR`, or `TEMP_DIR` environment variables are set, they will be treated as overrides and used by default. If the environment variables are not set, the paths are determined based on the specific conventions for each operating system (with additional overrides available through operating system specific environment variables):
   *
   * - **Linux**: directories are generally created in `~/.config/<name>` (this is determined via the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/latest/))
   *
   * - **Windows**: directories are generally created in `%AppData%/<name>`
   *
   * - **MacOS**: directories are generally created in `~/Library/Application Support/<name>`
   */
  export const paths: EnvPaths;
}
