
// Generated by powerlines
// Do not edit this file directly

export interface BaseExecutorSchema {
 /**
  * Powerlines Configuration File
  * 
  * The path to the Powerlines configuration file. Alias for `configFile`.
  * 
  * @default "{projectRoot}/powerlines.config.ts"
  * 
  * @format path
 */
 config?: string,

 /**
  * Powerlines Configuration File
  * 
  * The path to the Powerlines configuration file. Alias for `config`.
  * 
  * @default "{projectRoot}/powerlines.config.ts"
  * 
  * @format path
 */
 configFile?: string,

 /**
  * Input Entry File(s)
  * 
  * The entry file(s) that serve as the input for the project
  * 
  * 
  * @format path
 */
 input?: Array<string>,

 /**
  * TSConfig Path
  * 
  * The path to the tsconfig file
  * 
  * @default "{projectRoot}/tsconfig.json"
  * 
  * @format path
 */
 tsconfig?: string,

 /**
  * Output Path
  * 
  * The path to the output directory for the build artifacts
  * 
  * 
  * @format path
 */
 outputPath?: string,

 /**
  * Publish Path
  * 
  * The path to the publish directory for the build artifacts
  * 
  * 
  * @format path
 */
 publishPath?: string,

 /**
  * Sourcemap
  * 
  * Generate a sourcemap
  * 
 */
 sourceMap?: boolean,

 /**
  * Format
  * 
  * The format to build
  * 
  * @default ["cjs","esm"]
 */
 format?: Array<string>,

 /**
  * Platform
  * 
  * The platform to build
  * 
  * @default "neutral"
  * 
  * @enum neutral,node,browser
 */
 platform?: string,

 /**
  * External
  * 
  * The external dependencies
  * 
 */
 external?: Array<any>,

 /**
  * No External
  * 
  * The dependencies that should not be treated as external
  * 
 */
 noExternal?: Array<any>,

 /**
  * Skip Node Modules Bundle
  * 
  * Skip bundling node_modules during the build process (if required)
  * 
 */
 skipNodeModulesBundle?: boolean,

 /**
  * Mode
  * 
  * The build mode
  * 
  * 
  * @enum development,test,production
 */
 mode?: string,

 /**
  * Log Level
  * 
  * The log level to use for the build process
  * 
  * 
  * @enum fatal,error,warn,success,info,debug,trace,silent
 */
 logLevel?: string,

 /**
  * Define
  * 
  * The `define` values
  * 
 */
 define?: Record<string, string>,
}

